### ISSUE TITLE
Building on OpenSUSE 12.2

### ISSUE THREAD

**Issue by joshuisken** [mattn/growl-for-linux#32]
To build on opensuse 12.2 I has following issues:
- replace deprecated g_strcasecmp by g_ascii_strcasecmp
- to link with libgmodule-2.0 add LDFLAGS="-lgmodule-2.0" to either make or configure

I got following error:
/usr/lib/gcc/i586-suse-linux/4.7/../../../../i586-suse-linux/bin/ld: gol-gol.o: undefined reference to symbol 'g_module_close'
/usr/lib/gcc/i586-suse-linux/4.7/../../../../i586-suse-linux/bin/ld: note: 'g_module_close' is defined in DSO /usr/lib/libgmodule-2.0.so.0 so try adding it to the linker command line
/usr/lib/libgmodule-2.0.so.0: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status

Another issue: after rerunning './configure' I had to 'make clean', otherwise rebuild would not be done. I changed './configure prefix', after which I expect a rebuild...
